// Renders the owner-provided legal markdown (src/content/legal/*.md) into typed
// HTML modules the app imports at runtime, so the production bundle never needs
// a markdown library. `marked` is a devDependency used ONLY here; run this after
// editing either .md and COMMIT the generated *.html.ts. Idempotent.
//
//   pnpm legal:build   (== node scripts/build-legal.mjs)
import { marked } from "marked";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIR = path.join(root, "src", "content", "legal");

const DOCS = [
  { md: "privacy.md", out: "privacy.html.ts" },
  { md: "privacy.th.md", out: "privacy.th.html.ts" },
  { md: "terms.md", out: "terms.html.ts" },
  { md: "terms.th.md", out: "terms.th.html.ts" },
];

marked.setOptions({ gfm: true, breaks: false });

async function run() {
  for (const { md, out } of DOCS) {
    const src = await readFile(path.join(DIR, md), "utf8");
    const html = marked.parse(src).trim();
    const body =
      "// AUTO-GENERATED by scripts/build-legal.mjs from " +
      md +
      " — do not edit by hand.\n" +
      "// Re-run `pnpm legal:build` after changing the source markdown.\n" +
      "export const html = " +
      JSON.stringify(html) +
      ";\n";
    await writeFile(path.join(DIR, out), body, "utf8");
    console.log(`legal:build → ${out} (${html.length} chars)`);
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
