// GENERATED by scripts/optimize-landing-images.mjs — do not edit by hand.
// Run `pnpm images:landing` to regenerate.
export type LandingImageKey = "hero" | "playroom" | "cozy" | "studio" | "clay" | "passes" | "logo";
export type LandingImage = { src: string; srcset: string; width: number; height: number; widths: number[] };
export const landingImages: Record<LandingImageKey, LandingImage> = {
  "hero": {
    "src": "/landing/siamese-cat-creative-club-shop-front-bangkok-900.webp",
    "srcset": "/landing/siamese-cat-creative-club-shop-front-bangkok-480.webp 480w, /landing/siamese-cat-creative-club-shop-front-bangkok-768.webp 768w, /landing/siamese-cat-creative-club-shop-front-bangkok-900.webp 900w",
    "width": 900,
    "height": 1200,
    "widths": [
      480,
      768,
      900
    ]
  },
  "playroom": {
    "src": "/landing/supervised-indoor-childrens-playroom-bangkok-1200.webp",
    "srcset": "/landing/supervised-indoor-childrens-playroom-bangkok-480.webp 480w, /landing/supervised-indoor-childrens-playroom-bangkok-768.webp 768w, /landing/supervised-indoor-childrens-playroom-bangkok-1080.webp 1080w, /landing/supervised-indoor-childrens-playroom-bangkok-1200.webp 1200w",
    "width": 1200,
    "height": 1600,
    "widths": [
      480,
      768,
      1080,
      1200
    ]
  },
  "cozy": {
    "src": "/landing/cozy-family-lounge-area-1200.webp",
    "srcset": "/landing/cozy-family-lounge-area-480.webp 480w, /landing/cozy-family-lounge-area-768.webp 768w, /landing/cozy-family-lounge-area-1080.webp 1080w, /landing/cozy-family-lounge-area-1200.webp 1200w",
    "width": 1200,
    "height": 1600,
    "widths": [
      480,
      768,
      1080,
      1200
    ]
  },
  "studio": {
    "src": "/landing/kids-art-and-crayon-creative-studio-1200.webp",
    "srcset": "/landing/kids-art-and-crayon-creative-studio-480.webp 480w, /landing/kids-art-and-crayon-creative-studio-768.webp 768w, /landing/kids-art-and-crayon-creative-studio-1080.webp 1080w, /landing/kids-art-and-crayon-creative-studio-1200.webp 1200w",
    "width": 1200,
    "height": 1600,
    "widths": [
      480,
      768,
      1080,
      1200
    ]
  },
  "clay": {
    "src": "/landing/soft-clay-statue-making-activity-for-kids-900.webp",
    "srcset": "/landing/soft-clay-statue-making-activity-for-kids-480.webp 480w, /landing/soft-clay-statue-making-activity-for-kids-768.webp 768w, /landing/soft-clay-statue-making-activity-for-kids-900.webp 900w",
    "width": 900,
    "height": 1200,
    "widths": [
      480,
      768,
      900
    ]
  },
  "passes": {
    "src": "/landing/childrens-creative-activity-room-bangkok-900.webp",
    "srcset": "/landing/childrens-creative-activity-room-bangkok-480.webp 480w, /landing/childrens-creative-activity-room-bangkok-768.webp 768w, /landing/childrens-creative-activity-room-bangkok-900.webp 900w",
    "width": 900,
    "height": 1200,
    "widths": [
      480,
      768,
      900
    ]
  },
  "logo": {
    "src": "/landing/siamese-cat-creative-club-logo-512.webp",
    "srcset": "/landing/siamese-cat-creative-club-logo-256.webp 256w, /landing/siamese-cat-creative-club-logo-512.webp 512w",
    "width": 512,
    "height": 512,
    "widths": [
      256,
      512
    ]
  }
} as const;
